### ISSUE TITLE
This channel is not responding.

### ISSUE THREAD

**Issue by camrun91** [ngovil21/RequestChannel.bundle#53]
I just updated PMS this past week and updated the channel today. I Have not used the channel much but when I go to manage Couchpotato or Sickrage I get this channel is not responding. I get the same message when I search for a movie. I tried to locate the logs but with debugging on there are still not any logs to be found.

**Comment by ngovil21** [comment]
Check your CouchPotato and SickRage settings, to make sure it can connect. Try changing your Settings to use TheMovieDatabase for movies.

I will need to see logs which would be here:
https://support.plex.tv/hc/en-us/articles/201106148-Channel-Log-Files

You can email them to me at ngovil21@gmail.com

**Comment by camrun91** [comment]
I just emailed you the logs. I was over looking them earlier. I have not had a chance to look at them at all yet either.

**Comment by ngovil21** [comment]
Thanks for the logs. I pushed some changes from the development branch. Please check and see if it works properly now.

**Comment by camrun91** [comment]
OK it is working better but Still getting errors You want me to send you the most recent logs?

**Comment by ngovil21** [comment]
Yes please. Could you also describe where you are getting the errors?

**Comment by camrun91** [comment]
Let me double check today and make sure I am getting them. I will verifiy here and then send you the logs as well.

**Comment by camrun91** [comment]
OK so when I go to view requests then to movie requests and I clear completed I get the yes or no option. I click yes and it thinks about it and then gives me the this channel is not responding. Also from the main menu when I click manage couchpotato I get the message error connecting to couchpotato. I also get an error if I click manage sickrage I get the error retrieving sickrage tv shows or something like that. I am emailing you the logs in just a second.

**Comment by ngovil21** [comment]
So it looks like everything isn't able to connect, I think this may be more of a problem with your preferences.

Is your plex server on the same network as the other services, or even on the same machine? Try using the local address (192.168.1.xxx or 127.0.0.1) instead of your domain name. Sometimes the DNS querying can get messy if you don't do that.

When testing this, Preferences don't get applied until after you reload the channel, so change preferences then go back to the Plex home page -> Channels -> Request Channel.

**Comment by camrun91** [comment]
Ok this seems to be working now thank you!
